In [ ]:
import numpy as np

In [18]:
a = np.array([1,2,3] , dtype = 'int32')
print(a)

[1 2 3]


In [19]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [20]:
a.ndim

1

In [21]:
b.ndim

2

In [22]:
a.shape
b.shape

(2, 3)

In [23]:
a.shape

(3,)

In [24]:
a.dtype

dtype('int32')

In [25]:
b.dtype

dtype('int64')

In [26]:
a.itemsize

4

In [27]:
b.itemsize

8

In [28]:
a.nbytes

12

In [29]:
a.size

3

In [ ]:
c = np.array(
   [[1,2,3 ,4 ,5 ,6 ,7 ],
    [8,9,10,11,12,13,14]])
print(c[0,5])

6


In [32]:
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
c[:,3]

array([ 4, 11])

In [34]:
c[0,1:-1:2]

array([2, 4, 6])

In [35]:
c[1,5] = 69

In [36]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 69, 14]])

In [37]:
c[1,2:5:1] = [70,80,90]

In [38]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 70, 80, 90, 69, 14]])

In [39]:
d = np.array([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [7,8,9],[10,11,12]
    ]
])

In [40]:
d.ndim

3

In [41]:
d[0,1,2]

np.int64(6)

In [42]:
d[0,0,2] = 33

In [43]:
d

array([[[ 1,  2, 33],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
d[1,0:,1] = [88,1111]

In [45]:
d

array([[[   1,    2,   33],
        [   4,    5,    6]],

       [[   7,   88,    9],
        [  10, 1111,   12]]])

In [46]:
e = np.zeros((4,4))

In [47]:
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
f = np.ones((3,3,3))
print(f)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [49]:
g = np.full((2,2),99,dtype='float32')
print(g)

[[99. 99.]
 [99. 99.]]
